version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    volumes:
      - .:/server
    networks:
      - default
    depends_on:
      # - redis
      - mongo
  # redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - default
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      # MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      # MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_PASSWORD: ${MONGO_PASS}
      MONGO_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongo:/data/db
      # - ./data:/data/db if you want to use a volume 
    networks:
      - default
networks:
  default:
volumes:
  mongo:


    

      